<?php


function wills_form_menu(){
	
	$items = array();
	
	$items['examples/form'] = array(
		'title' => 'My new form',
		'description' => ' new form ceated',
		'page callback' => 'drupal_get_form',
		'page arguments' => array(' wills_form_config_block'),
		'access callback' => true
	);
		$items['admin/config/search/wills-config'] = array(
		'title' => 'wills config for site',
		'description' => ' new page ceated',
		'page callback' => 'drupal_get_form',
		'page arguments' => array( 'wills_form_config_block'),
       'access arguments' => array('access administration pages'),
		'weight' => -10,
	);
	$items['examples/newpg/%'] = array(
		'title' => 'My new page',
		'description' => ' new page ceated',
		 'type' => MENU_NORMAL_ITEM,
		'page callback' => 'system_admin_menu_block_page',
       'access arguments' => array('access content'),
	);
	

	  $items['admin/config/search/wills-config/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

	$items['admin/config/search/wills-config/task1'] = array(
		'title' => 'wills config for site task 1',
		'description' => ' new page ceated config task 1',
		'type' => MENU_LOCAL_TASK,
		'weight' => 10,
		'page callback' => 'wills_form_config_block_task1',
       'access arguments' => array('access administration pages'),
	);
	return $items ;
}
function wills_form_config_block_task1(){
	  return 'works task 1';
  }
  function wills_form_config_block($form,  &$form_state){
	$form = array();
	
	$form = generate_form($form,$form_state);
	return $form;
  
  }
  
  function generate_form($form,&$form_state=null){

	  
	  $form['group1'] = array(
	  '#type' => 'fieldset',
	  '#title' => t('Personal Details '),
	  '#collapsible' => false,
	  '#collapsed' => false,
	  //'#prefix' => '<div id="div-per">',
	  //'#suffix' => '</div>',
	 //  '#attributes' => array( 'class' => array( 'panel'))
	);

	$form['group1']['first_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('First Name'),
	 
	);
  
	$form['group1']['last_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Last Name'),
	);
	
	$form['group1']['education_option'] = array(
		'#type' => 'radios',
		'#title' => t('Eduction'),
		'#options' => array(0 =>t('No'),1=>t('Yes')	  ),
	  '#default_value'=> 0,
	  '#ajax' => array(
				  'callback' => 'ajax_example_autocheckboxes_callback',
				  'wrapper' => 'will-div',
				 // 'method' => 'replace',
				  'effect' => 'fade',
				),
	);
	
		if(isset($form_state["values"]["education_option"]) && ($form_state["values"]["education_option"]>0))
			{
					$form = education_group($form);	
					if($form_state["values"]["wrk_option"]>0){
						$form = work_group($form);
					}
					
					//print("tim");
			}
			else{
				$form["will"] = array(
						"#type" =>'markup',
						'#prefix' =>'<div id="will-div" style="background-color:red"  class=""> hi',
						'#suffix' => '</div>',
					);
				 $form["html2"] = array(
						"#type" =>'markup',
						'#markup' =>'<div id="div-wrk"  class=""></div>'
					);
					
			}
		//$form = work_group($form);
		
	return $form;
  }
  function education_group($form){
	  $form["will"] = array(
						"#type" =>'markup',
						'#prefix' =>'<div id="will-div" style="background-color:red"  class=""> hi',
						'#suffix' => '</div>',
					);
	$form['will']['group2'] = array(
	  '#type' => 'fieldset',
	  '#title' => t('Eduction '),
	  '#collapsible' => false,
	  '#collapsed' => false,
	  '#prefix' => '<div id="div-will"   style="background-color:red; margin-bottom:20px">',
	  '#suffix' => '</div>',
	 //  '#attributes' => array( 'class' => array( 'panel'))
	);

	$form['will']['group2']['first_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('First Name'),
	 
	);

	$form['will']['group2']['last_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Last Name'),
	);
	$form['will']['group2']['wrk_option'] = array(
		'#type' => 'radios',
		'#title' => t('Work'),
		'#options' => array(0 =>t('No'),1=>t('Yes')	  ),
	  '#default_value'=> 0,
	  '#ajax' => array(
				  'callback' => 'work_group_radio_callback',
				  'wrapper' => 'div-wrk',
				 // 'method' => 'replace',
				  'effect' => 'fade',
				),
	);
	
	return $form;
  
  }
  
  
  
  function work_group($form){
	  
	  $form['will']['group3'] = array(
	  '#type' => 'fieldset',
	  '#title' => t('Work'),
	  '#collapsible' => false,
	  '#collapsed' => false,
	  
	  '#prefix' => '<div id="div-wrk"   style="margin-bottom:20px">',
	  '#suffix' => '</div>',
	 //  '#attributes' => array( 'class' => array( 'panel'))
	);

	$form['will']['group3']['first_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('First Name'),
	 
	);

	$form['will']['group3']['last_name'] = array(
	  '#type' => 'textfield',
	  '#title' => t('Last Name'),
	);  
	  return $form;
  }
     /// 
	function wills_form_page(){
		$content = 'wills page  ';
		return $content;
	}
	function wills_form_page_form($form, &$form_state){
		$form = array();
		$form = generate_form($form, $form_state);
	
		$form['submit_button'] = array(
				'#type' => 'submit',
				'#value'  => t('click me'),
				
		);
		return $form;
	}
	
	function wills_form_page_form_validate($form, &$form_state){
		
		if(!($form_state['values']['price']>0)){
				form_set_error('price',t('price must be positive'));
		}
		if(strlen($form_state['values']['name'])>7){
				form_set_error('name',t('name is greater than seven characters'));
		}
		
	}
	
	function wills_form_page_form_submit($form, &$form_state){
		drupal_set_message( t('submitted  '). $form_state['values']['price']);
	}

	
	
	
	
	
	
	
	/**
 * Callback element needs only select the portion of the form to be updated.
 * Since #ajax['callback'] return can be HTML or a renderable array (or an
 * array of commands), we can just return a piece of the form.
 */
function ajax_example_autocheckboxes_callback($form, &$form_state) {
	//print_r($form["group1"]["education_option"]['#options']);
	//$ed_option = $form["education_option"];
	if($form_state["values"]["education_option"]>0){
		
		return $form['will'];
	}
		
	else{
		 
		return  '<div id="div-will" style="background-color:red">  tim</div>';
	}
	
}

function work_group_radio_callback($form, &$form_state){
	if($form_state["values"]["wrk_option"]>0){
		
		return $form['will']['group3'];
	}
		
	else{
		return  '<div id="div-wrk">  </div>';
	}
}
?>